language: python
python:
  - "3.5"
  - "3.6"
dist: trusty
sudo: required
script:
  - flake8
  - pytest -v --benchmark-skip --minimal-pulseaudio-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y psmisc pulseaudio
install: "pip install -r requirements.txt"
notifications:
  email: false

